/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#ffffff',
        'secondary-container': '#dbeafe',
        'on-surface': '#1e293b',
        'surface-bright': '#f8fafc',
        'inverse-on-surface': '#f1f5f9',
        'primary-fixed-dim': '#93c5fd',
        'surface-container-high': '#e2e8f0',
        'surface-tint': '#2563eb',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#cbd5e1',
        'on-tertiary': '#ffffff',
        'background': '#f8fafc',
        'on-tertiary-container': '#1e40af',
        'outline': '#64748b',
        'tertiary-container': '#1e40af',
        'on-secondary-container': '#1e3a8a',
        'surface-container-highest': '#cbd5e1',
        'outline-variant': '#94a3b8',
        'on-primary': '#ffffff',
        'inverse-surface': '#0f172a',
        'primary-fixed': '#dbeafe',
        'secondary': '#475569',
        'on-surface-variant': '#475569',
        'on-primary-fixed': '#1e3a8a',
        'on-tertiary-fixed-variant': '#1e3a8a',
        'on-primary-fixed-variant': '#2563eb',
        'tertiary-fixed': '#bfdbfe',
        'on-tertiary-fixed': '#1e3a8a',
        'on-background': '#0f172a',
        'on-secondary-fixed': '#1e3a8a',
        'inverse-primary': '#93c5fd',
        'tertiary-fixed-dim': '#3b82f6',
        'on-error': '#ffffff',
        'secondary-fixed': '#dbeafe',
        'on-error-container': '#991b1b',
        'on-secondary': '#ffffff',
        'surface': '#f8fafc',
        'error': '#ef4444',
        'on-secondary-fixed-variant': '#1e40af',
        'primary-container': '#2563eb',
        'primary': '#1e40af',
        'surface-container': '#f1f5f9',
        'surface-container-low': '#f8fafc',
        'tertiary': '#1e40af',
        'secondary-fixed-dim': '#93c5fd',
        'surface-variant': '#e2e8f0',
        'error-container': '#fee2e2',
        'blue-accent': '#2563eb',
        'blue-light': '#eff6ff'
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px'
      },
      fontFamily: {
        headline: ['Manrope', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        body: ['Inter', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        label: ['Inter', 'PingFang SC', 'Microsoft YaHei', 'sans-serif']
      }
    },
  },
  plugins: [],
}
